name: myky_clone
description: Ecommerce App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.1+23

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.5
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.1
  get: ^4.6.6
  cached_network_image: ^3.3.0
  image_picker: ^1.0.5
  datetime_picker_formfield: ^2.0.1
  date_format: ^2.0.7
  flutter_paginator_ns: ^2.0.0
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  permission_handler: ^11.3.0
  path_provider: ^2.1.1
  share_plus: ^7.2.2
  flutter_cached_pdfview: ^0.4.0-nullsafety
  http: ^1.2.0
  url_launcher: ^6.0.10
  liquid_pull_to_refresh: ^3.0.1
#  image_picker_gallery_camera: ^0.2.2
  flutter_downloader: ^1.5.0
  photo_view: ^0.14.0
  nb_utils: ^6.1.2
  flutter_html: ^3.0.0-beta.2
  hexcolor: ^3.0.1
  flutter_inappwebview: ^6.0.0
  unicons: ^2.0.2
  like_button: ^2.0.5
  device_info_plus: ^9.1.2
  package_info: ^2.0.2
  youtube_player_flutter: ^9.0.0-beta.0
  fl_chart: ^0.40.2
  shimmer: ^3.0.0
  bubble: ^1.2.1
  firebase_messaging: ^14.7.15
  firebase_core: ^2.24.2
  firebase_messaging_platform_interface: ^4.5.23
  flutter_local_notifications: ^16.3.2
  firebase_dynamic_links: ^5.4.13
  video_player: ^2.9.1
  percent_indicator: ^4.2.3
  flutter_barcode_scanner: ^2.0.0
  google_maps_flutter: ^2.5.3
  geolocator: ^9.0.2
  volume_control: ^0.1.5
  flutter_tts: ^3.8.5
  translator: ^1.0.0
  paytm_allinonesdk: ^1.2.4
  flutter_screenutil: ^5.9.0
  video_thumbnail: ^0.5.3
  numeral: ^3.0.0
  flutter_rating_bar: ^4.0.1
  open_filex: ^4.4.0
#  external_path: ^1.0.3
  another_stepper: ^1.2.2
  wakelock_plus: ^1.0.0+3
  platform: ^3.1.4
  pdfx: ^2.6.0
  android_id: ^0.3.6
  external_path: ^1.0.3
  ntp: ^2.0.0
  intl: ^0.19.0
  flutter_custom_clippers: ^2.0.0
  dropdown_button2: ^2.3.9
  file_picker: ^8.0.0+1
  image_cropper: ^5.0.1
  boxicons: ^2.1.3
  pinch_zoom: ^2.0.0
  dotted_line: ^3.2.2
  external_app_launcher: ^4.0.0
  map_launcher: ^3.5.0
  search_choices: 2.2.6
  google_mobile_ads: ^4.0.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_upi_india: ^0.0.6
  mobile_scanner: ^5.1.1
  flutter_confetti: ^0.2.0
  carousel_slider: ^5.1.1


#  platform_device_id: ^1.0.1

#  flutter_webview_plugin:
#    git: https://github.com/snoopdoggy322/flutter_webview_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/launcher/myky_app_icon_1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/launcher/
    - assets/images/winners/
    - assets/static-images/
    - assets/paymentAppIcon/
    - assets/images/tab/
    - assets/video/
    - .env.stage
    - .env.local
    - .env.live


  fonts:
    - family: ExtraLight
      fonts:
        - asset: assets/fonts/Sora-ExtraLight.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/Sora-Light.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf

    - family: SemiBold
      fonts:
        - asset: assets/fonts/Sora-SemiBold.ttf

    - family: Bold
      fonts:
        - asset: assets/fonts/Sora-Bold.ttf

    - family: ExtraBold
      fonts:
        - asset: assets/fonts/Sora-ExtraBold.ttf